services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: loehoedp/vprofiledb:latest
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vproapp:
    build:
      context: ./Docker-files/app
    image: loehoedp/vprofileapp:latest
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: loehoedp/vprofileweb:latest
    container_name: vproweb
    ports:
      - "80:80"

  vprocache01:
    image: memcached:latest
    ports:
      - 11211:11211
  
  vpromq01:
    image: rabbitmq:latest
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER= guest
      - RABBITMQ_DEFAULT_PASS= guest

volumes:
  vprodbdata: {}
  vproappdata: {}

